/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DarkModeButton: typeof import('./src/components/DarkModeButton.vue')['default']
    MenuItem: typeof import('./src/components/MenuItem.vue')['default']
    MenuList: typeof import('./src/components/MenuList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleButton: typeof import('./src/components/SingleButton.vue')['default']
    SiteLogo: typeof import('./src/components/SiteLogo.vue')['default']
  }
}
